# Generated by Django 4.1.1 on 2023-01-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student_tb',
            },
        ),
    ]
