# Generated by Django 4.1.1 on 2023-01-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_seller_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='action',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
